apiVersion: v1
kind: Service
metadata:
        name: myservice
        labels:
                app: mypod
spec:
        ports:
                - port: 8080
                  targetPort: 80
        type: LoadBalancer
        selector:
                app: mypod
