apiVersion: v1
kind: Service
metadata:
        name: ser-data-tier
        labels:
                tier: svc-data
spec:
        ports:
                - port: 8080
        selector:
                tier: data
        type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: pod-data-tier
        labels:
                tier: data
spec:
        replicas: 1
        selector:
                matchLabels:
                        tier: data
        template:
                metadata:
                        labels:
                                tier: data
                spec:
                        containers:
                                - name: mycont
                                  image: ubuntu
                                  #ports:
                                        #-  containerPort: 8080
                                  env:
                                        - name: DATA_SVC
                                          value: datalink
                                  command:
                                          - cat
                                          - "/etc/vol/prop.txt"
                                  volumeMounts:
                                          - mountPath: "/etc/vol"
                                            name: myvol
                        volumes:
                                - name: myvol
                                  configMap:
                                          name: myconfig   
                                          items:                                
                                                - key: conf
                                                  path: prop.txt

