apiVersion: v1
kind: Service
metadata:
        name: ser-data-tier
        labels:
                tier: svc-data
spec:
        ports:
                - port: 8080
        selector:
                tier: data
        type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: pod-data-tier
        labels:
                tier: data
spec:
        replicas: 1
        selector:
                matchLabels:
                        tier: data
        template:
                metadata:
                        labels:
                                tier: data
                spec:
                        containers:
                                - name: mycont
                                  image: redis:latest
                                  ports:
                                          -  containerPort: 6379
                                             name: redisxx
                                  livenessProbe:
                                          tcpSocket:
                                                  port: redisxx
                                          initialDelaySeconds: 15
                                  readinessProbe:
                                          exec:
                                                  command:
                                                          - redis-cli
                                                          - ping
                                          initialDelaySeconds: 15

