apiVersion: v1
kind: Pod
metadata:
        name: mypod
        labels:
                app: pod
                tier: back
spec:
        containers:
                - name: mypod
                  image: nginx
                  ports:
                          - containerPort: 80
                            name: nginxcont
                  livenessProbe:
                          exec:
                                  command: ["/bin/bash", "-c","echo 'liveness Probe is success' > text.txt"]
                          initialDelaySeconds: 15
                  readinessProbe:
                          tcpSocket:
                                  port: nginxcont
                          initialDelaySeconds: 7        
