apiVersion: v1
kind: Pod
metadata:
        name: mypod
spec:
        containers:
                - name: mycont
                  image: nginx
                  ports:
                          - containerPort: 80
        initContainers:
                - name: myinit
                  image: ubuntu
                  command: ["/bin/bash","-c","echo 'india is my country, but not yours' > txt.ind && sleep 120"]
