apiVersion: v1
kind: Pod
metadata:
        name: mypod
        labels:
                app: mypod
spec:
        containers:
                - name: mypod
                  image: nginx
                  imagePullPolicy: IfNotPresent
        restartPolicy: Never    
