apiVersion: v1
kind: Pod
metadata:
        name: mypod
        labels:
                app: mypod
                itmAdded: label
spec:
        containers:
                - name: mypod
                  image: nginx 
                  imagePullPolicy: IfNotPresent
                  ports:
                          - containerPort: 80
                  env:
                          - name: "APP_SVC"
                            value: ""
        restartPolicy: Never
