apiVersion: v1
kind: Pod
metadata:
        name: mypod
        labels:
                app: mypod
spec:
        containers:
                - name: mypod
                  image: nginx
                  imagePullPolicy: IfNotPresent
                  ports:
                          - containerPort: 80
                  resources:
                          requests:
                                  cpu: "100m"
                                  memory: "100Mi"
                          limits:
                                   cpu: "250m"
                                   memory: "150Mi"                                                     
        restartPolicy: Never
