apiVersion: v1
kind: Pod
metadata:
        name: confpod
        labels:
                app: myconf
spec:
        containers:
                - name: myconf
                  image: nginx
                  ports:
                          - containerPort: 80
                  volumeMounts:
                          - mountPath: "/conf/data"
                            name: myvol
        restartPolicy: Always
        volumes:
                - name: myvol
                  configMap:
                          name: conf
                          items:
                                  - key: country
                                    path: "conf.log"
