apiVersion: v1
kind: Pod
metadata:
        name: envpod
        labels:
                app: conf
spec:
        containers:
                - name: mycont
                  image: nginx
                  env:
                          - name: "myconf"
                            valueFrom:
                                    configMapKeyRef:
                                            name: conf
                                            key: desc
        restartPolicy: Never

