apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: nginx
      ports:
              - containerPort: 80
      command: ["/bin/bash", "-c","cat /app/config/conf.log"]  
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: my-volume
          mountPath: /app/config
  volumes:
    - name: my-volume
      configMap:
        name: conf
        items:
                - key: desc
                  path: conf.log
