apiVersion: apps/v1
kind: Deployment
metadata:
        name: {{ include "myhelm.fullname" . }}
        labels:
                app: myhelm
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: {{ .Values.myhelm.labels }}
        template:
                metadata:
                        name: mypod
                        labels:
                                app: {{ .Values.myhelm.labels }}
                spec:
                        containers:
                                - name: {{ .Values.containers.name }}
                                  image: {{ .Values.containers.image }}
                                  ports:
                                          - containerPort: {{ .Values.containers.port }}
                                            name: ngin
                                  livenessProbe:
                                          httpGet:
                                                  path: /
                                                  port: ngin
                                          initialDelaySeconds: {{ .Values.containers.ready.delay }}

