apiVersion: v1
kind: PersistentVolume 
metadata:
        name: myvol
        labels:
                app: volapp
spec:
        capacity:
                storage: "300m"
        accessModes: 
                - ReadWriteMany
        nfs:
                path: "/mnt/my_shares"
                readOnly: false
                server: 10.0.0.5
